from .models import FailureCode, FailureCategory, FailureDiagnosis

TAXONOMY = {
    FailureCode.UPI_TIMEOUT: {
        "category": FailureCategory.TRANSIENT,
        "description": "NPCI/PSP bank switch timed out waiting for beneficiary bank ACK.",
        "is_retryable": True,
        "recommended_wait_minutes": 20,
        "customer_action_required": False,
        "upi_specific": True,
    },
    FailureCode.UPI_BANK_UNAVAILABLE: {
        "category": FailureCategory.TRANSIENT,
        "description": "Issuer CBS (Core Banking Solution) is undergoing maintenance or experiencing downtime.",
        "is_retryable": True,
        "recommended_wait_minutes": 45,
        "customer_action_required": False,
        "upi_specific": True,
    },
    FailureCode.UPI_INSUFFICIENT_BALANCE: {
        "category": FailureCategory.CUSTOMER_ACTION_REQUIRED,
        "description": "Customer bank account balance insufficient for UPI debit.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": True,
    },
    FailureCode.UPI_INVALID_VPA: {
        "category": FailureCategory.PAYMENT_METHOD_PROBLEM,
        "description": "Virtual Payment Address does not exist or has been deactivated.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": True,
    },
    FailureCode.UPI_PSP_FAILURE: {
        "category": FailureCategory.TRANSIENT,
        "description": "PSP app gateway (PhonePe/GPay/Paytm) returned internal error.",
        "is_retryable": True,
        "recommended_wait_minutes": 10,
        "customer_action_required": False,
        "upi_specific": True,
    },
    FailureCode.CUSTOMER_CANCELLED: {
        "category": FailureCategory.PERMANENT,
        "description": "Customer deliberately dismissed payment prompt or clicked Cancel.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": False,
    },
    FailureCode.CARD_EXPIRED: {
        "category": FailureCategory.PAYMENT_METHOD_PROBLEM,
        "description": "Credit/Debit card expiry month/year is in the past.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": False,
    },
    FailureCode.CARD_DECLINED: {
        "category": FailureCategory.POTENTIALLY_RISKY,
        "description": "Card issuing bank blocked charge due to velocity limits or risk check.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": False,
    },
    FailureCode.CARD_INSUFFICIENT_FUNDS: {
        "category": FailureCategory.CUSTOMER_ACTION_REQUIRED,
        "description": "Credit limit reached or insufficient debit card balance.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": False,
    },
    FailureCode.CARD_AUTHENTICATION_FAILURE: {
        "category": FailureCategory.POTENTIALLY_RISKY,
        "description": "3DS OTP entered incorrectly or session expired during RBI-mandated 2FA.",
        "is_retryable": True,
        "recommended_wait_minutes": 5,
        "customer_action_required": True,
        "upi_specific": False,
    },
    FailureCode.NETWORK_ERROR: {
        "category": FailureCategory.TRANSIENT,
        "description": "Socket reset or packet drop between merchant payment SDK and gateway.",
        "is_retryable": True,
        "recommended_wait_minutes": 5,
        "customer_action_required": False,
        "upi_specific": False,
    },
    FailureCode.MANDATE_PAUSED: {
        "category": FailureCategory.CUSTOMER_ACTION_REQUIRED,
        "description": "Customer paused UPI AutoPay / e-mandate via UPI app.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": True,
    },
    FailureCode.MANDATE_REVOKED: {
        "category": FailureCategory.PERMANENT,
        "description": "Customer cancelled recurring standing instruction mandate completely.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": True,
    },
    FailureCode.BANK_DECLINED: {
        "category": FailureCategory.POTENTIALLY_RISKY,
        "description": "Acquiring bank or clearing house declined the transaction.",
        "is_retryable": False,
        "recommended_wait_minutes": 0,
        "customer_action_required": True,
        "upi_specific": False,
    },
}

def diagnose_failure(code: FailureCode) -> FailureDiagnosis:
    meta = TAXONOMY.get(code, {
        "category": FailureCategory.TRANSIENT,
        "description": "Generic payment failure encountered.",
        "is_retryable": True,
        "recommended_wait_minutes": 15,
        "customer_action_required": False,
        "upi_specific": False,
    })
    return FailureDiagnosis(
        failure_code=code,
        category=meta["category"],
        description=meta["description"],
        is_retryable=meta["is_retryable"],
        recommended_wait_minutes=meta["recommended_wait_minutes"],
        customer_action_required=meta["customer_action_required"],
        upi_specific=meta["upi_specific"],
    )
